// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPMtK4Wkn97y7UQSPKgnF785WwLkHjsso',
    appId: '1:809502550796:web:5c466600f6f346258e3729',
    messagingSenderId: '809502550796',
    projectId: 'pmsn2024b-3fe2c',
    authDomain: 'pmsn2024b-3fe2c.firebaseapp.com',
    storageBucket: 'pmsn2024b-3fe2c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCB2PlAd1LDD1h8VQpEBhVUOLiUBrE_ou4',
    appId: '1:809502550796:android:7a797d35cd4346e58e3729',
    messagingSenderId: '809502550796',
    projectId: 'pmsn2024b-3fe2c',
    storageBucket: 'pmsn2024b-3fe2c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTOvigQtOISh589am-_TvZhBKSzWnezHU',
    appId: '1:809502550796:ios:2cf1868aeb882c988e3729',
    messagingSenderId: '809502550796',
    projectId: 'pmsn2024b-3fe2c',
    storageBucket: 'pmsn2024b-3fe2c.appspot.com',
    iosBundleId: 'com.example.pmsn2024b',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTOvigQtOISh589am-_TvZhBKSzWnezHU',
    appId: '1:809502550796:ios:2cf1868aeb882c988e3729',
    messagingSenderId: '809502550796',
    projectId: 'pmsn2024b-3fe2c',
    storageBucket: 'pmsn2024b-3fe2c.appspot.com',
    iosBundleId: 'com.example.pmsn2024b',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAPMtK4Wkn97y7UQSPKgnF785WwLkHjsso',
    appId: '1:809502550796:web:3c18a0c3b48dd4ec8e3729',
    messagingSenderId: '809502550796',
    projectId: 'pmsn2024b-3fe2c',
    authDomain: 'pmsn2024b-3fe2c.firebaseapp.com',
    storageBucket: 'pmsn2024b-3fe2c.appspot.com',
  );
}
